### PR TITLE
The sploosh. 

### PR DESCRIPTION
**Pull request by moondroidcoder**

### CODE REVIEW

**Comment by CyndaquilDAC** [comment]
1. This can't be added until week 7 comes out on github.
2. what is with all the excess commits

**Comment by zacksgamerz** [comment]
1. Kol could make his own notesplash assets
2. I commit stuff like this lol.

**Comment by y579** [comment]
> * This can't be added until week 7 comes out on github.
> * what is with all the excess commits

**Kade engine has it tho?**

**Comment by CyndaquilDAC** [comment]
> > * This can't be added until week 7 comes out on github.
> > * what is with all the excess commits
> 
> **Kade engine has it tho?**

no?

**Comment by somefnfplayerlol** [comment]
> > * This can't be added until week 7 comes out on github.
> > * what is with all the excess commits
> 
> **Kade engine has it tho?**

kade engine itself does not feature note splashes, some custom builds do tho

**Comment by isakube** [comment]
> 1. This can't be added until week 7 comes out on github.
> 2. what is with all the excess commits

istg idk what repo it was but i saw a screenshot of MtH saying shit like note splashes could be used

actual week 7 content isn't allowed, but the rest is.
lemee try to find it

**Pull request closed without merging**
